services:
  redis:
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - redis:/data
      
  flassklist:
    image: ghcr.io/babatonga/flassklist:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - PGID=1000
      - PUID=1000
      - COMB_USE_PROXY=True
      - COMB_REDIS_URL=redis://redis:6379
    volumes:
      - /path/to/comb/data:/passlistdata
      #- /path/to/tmpfs:/ramdiskdata # optional ramdisk (tmpfs) for faster access
    depends_on:
      - redis

volumes:
  redis:
    driver: local